# Generated by Django 5.2.5 on 2025-09-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_useraddress'),
    ]

    operations = [
    ]
