# Generated by Django 5.2.5 on 2025-09-24 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250924_2132'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-id'], 'verbose_name': 'Coupon Code', 'verbose_name_plural': 'Coupon Codes'},
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to use this coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1, help_text='How many times this coupon can be used'),
        ),
        migrations.AddField(
            model_name='discount',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for all users', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discount',
            name='user_type',
            field=models.CharField(choices=[('all', 'All Users'), ('specific', 'Specific User Only'), ('first_order', 'First Order Bonus')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Leave blank to start from creation time', null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Applied coupon code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount from coupon', max_digits=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter percentage (e.g., 10 for 10%) or fixed amount', max_digits=10),
        ),
    ]
