# Generated by Django 5.2.5 on 2025-09-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_coupon_alter_usernotification_coupon_usercoupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Upload .glb 3D model file for AR/3D preview', null=True, upload_to='models/'),
        ),
    ]
