# Generated by Django 5.2.4 on 2025-10-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_tracking_id_to_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Has stock been deducted for this order?'),
        ),
    ]
