# Generated by Django 5.2.5 on 2025-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_return_reason_order_return_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returning', 'Returning'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
    ]
