# Generated by Django 5.2.7 on 2025-10-30 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_order_delivered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_item', models.DecimalField(decimal_places=2, help_text='Additional charge per item', max_digits=10)),
                ('estimated_time', models.PositiveIntegerField(help_text='Estimated time in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assembly Service',
                'verbose_name_plural': 'Assembly Services',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='showrooms/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Showroom',
                'verbose_name_plural': 'Showrooms',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(help_text='YouTube or video URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assembly_thumbnails/')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_videos', to='core.product')),
            ],
            options={
                'verbose_name': 'Assembly Video',
                'verbose_name_plural': 'Assembly Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='For guest users', max_length=40, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'verbose_name_plural': 'Chat Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatconversation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Sarah & John\'s Wedding"', max_length=200)),
                ('registry_type', models.CharField(choices=[('wedding', 'Wedding'), ('housewarming', 'Housewarming'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('other', 'Other')], default='wedding', max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('unique_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_registries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gift Registry',
                'verbose_name_plural': 'Gift Registries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftRegistryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(default=1)),
                ('quantity_purchased', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('high', 'Must Have'), ('medium', 'Would Love'), ('low', 'Nice to Have')], default='medium', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.giftregistry')),
            ],
            options={
                'verbose_name': 'Registry Item',
                'verbose_name_plural': 'Registry Items',
            },
        ),
        migrations.CreateModel(
            name='GroupPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('unique_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Group Purchase',
                'verbose_name_plural': 'Group Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupPurchaseContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, help_text='Optional message to organizer')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contributions', to=settings.AUTH_USER_MODEL)),
                ('group_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.grouppurchase')),
            ],
            options={
                'verbose_name': 'Group Purchase Contribution',
                'verbose_name_plural': 'Group Purchase Contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=6)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in inches', max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in lbs', max_digits=6)),
                ('seating_capacity', models.PositiveIntegerField(blank=True, help_text='For seating furniture', null=True)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('assembly_required', models.BooleanField(default=True)),
                ('assembly_time', models.PositiveIntegerField(blank=True, help_text='Estimated assembly time in minutes', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Dimension',
                'verbose_name_plural': 'Product Dimensions',
            },
        ),
        migrations.CreateModel(
            name='RoomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "My Living Room"', max_length=200)),
                ('room_type', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('dining_room', 'Dining Room'), ('office', 'Office'), ('kitchen', 'Kitchen'), ('other', 'Other')], default='living_room', max_length=20)),
                ('room_width', models.DecimalField(decimal_places=2, help_text='Width in feet', max_digits=6)),
                ('room_length', models.DecimalField(decimal_places=2, help_text='Length in feet', max_digits=6)),
                ('room_height', models.DecimalField(decimal_places=2, default=10, help_text='Height in feet', max_digits=6)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='room_designs/')),
                ('design_data', models.JSONField(default=dict, help_text='JSON data storing product positions')),
                ('is_public', models.BooleanField(default=False, help_text='Share with community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Design',
                'verbose_name_plural': 'Room Designs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomDesignProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('position_y', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rotation', models.IntegerField(default=0, help_text='Rotation angle in degrees')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('room_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.roomdesign')),
            ],
            options={
                'verbose_name': 'Room Design Product',
                'verbose_name_plural': 'Room Design Products',
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('technician_notes', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='core.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assemblyservice')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Booking',
                'verbose_name_plural': 'Service Bookings',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('panorama_image', models.ImageField(help_text='360° panoramic image', upload_to='panoramas/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.showroom')),
            ],
            options={
                'verbose_name': 'Showroom Scene',
                'verbose_name_plural': 'Showroom Scenes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.DecimalField(decimal_places=2, help_text='X position (0-100%)', max_digits=5)),
                ('position_y', models.DecimalField(decimal_places=2, help_text='Y position (0-100%)', max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='core.showroomscene')),
            ],
            options={
                'verbose_name': 'Showroom Hotspot',
                'verbose_name_plural': 'Showroom Hotspots',
            },
        ),
        migrations.CreateModel(
            name='StylePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_style', models.CharField(choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('minimalist', 'Minimalist'), ('rustic', 'Rustic'), ('industrial', 'Industrial'), ('scandinavian', 'Scandinavian'), ('bohemian', 'Bohemian')], max_length=20)),
                ('secondary_style', models.CharField(blank=True, choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('minimalist', 'Minimalist'), ('rustic', 'Rustic'), ('industrial', 'Industrial'), ('scandinavian', 'Scandinavian'), ('bohemian', 'Bohemian')], max_length=20)),
                ('preferred_colors', models.JSONField(default=list, help_text='List of preferred colors')),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_types', models.JSONField(default=list, help_text="Types of rooms they're furnishing")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Style Preference',
                'verbose_name_plural': 'Style Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserBrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in seconds')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Browsing History',
                'verbose_name_plural': 'Browsing History',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Recommendation strength (0-100)', max_digits=5)),
                ('reason', models.CharField(blank=True, help_text='Why this is recommended', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_with', to='core.product')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Recommendation',
                'verbose_name_plural': 'Product Recommendations',
                'ordering': ['-score'],
                'unique_together': {('product', 'recommended_product')},
            },
        ),
    ]
