# Generated by Django 5.2.7 on 2025-10-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_assemblyservice_showroom_assemblyvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdesign',
            name='design_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data storing product positions (optional)', null=True),
        ),
    ]
