# Generated by Django 5.2.7 on 2025-10-30 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_roomdesign_design_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add_product', 'Add Product'), ('remove_product', 'Remove Product'), ('move_product', 'Move Product'), ('rotate_product', 'Rotate Product'), ('edit_room', 'Edit Room'), ('other', 'Other')], max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Previous state data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Design History',
                'verbose_name_plural': 'Design Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='roomdesignproduct',
            options={'ordering': ['z_index', 'added_at'], 'verbose_name': 'Room Design Product', 'verbose_name_plural': 'Room Design Products'},
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='canvas_snapshot',
            field=models.TextField(blank=True, help_text='Base64 encoded canvas image', null=True),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='description',
            field=models.TextField(blank=True, help_text='Design description', null=True),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Is this a design template?'),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='likes',
            field=models.IntegerField(default=0, help_text='Number of likes'),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='room_color',
            field=models.CharField(default='#f3f4f6', help_text='Room wall color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='room_designs/thumbnails/'),
        ),
        migrations.AddField(
            model_name='roomdesign',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of views'),
        ),
        migrations.AddField(
            model_name='roomdesignproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomdesignproduct',
            name='scale',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Scale multiplier', max_digits=3),
        ),
        migrations.AddField(
            model_name='roomdesignproduct',
            name='z_index',
            field=models.IntegerField(default=0, help_text='Layer ordering'),
        ),
        migrations.AlterField(
            model_name='roomdesign',
            name='design_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data storing product positions', null=True),
        ),
        migrations.AlterField(
            model_name='roomdesignproduct',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='roomdesignproduct',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='roomdesignproduct',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Rotation angle in degrees (0-360)'),
        ),
        migrations.AddIndex(
            model_name='roomdesign',
            index=models.Index(fields=['user', '-updated_at'], name='core_roomde_user_id_19c162_idx'),
        ),
        migrations.AddIndex(
            model_name='roomdesign',
            index=models.Index(fields=['is_template', '-likes'], name='core_roomde_is_temp_4c3e6b_idx'),
        ),
        migrations.AddField(
            model_name='designhistory',
            name='room_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.roomdesign'),
        ),
    ]
