# Generated by Django 5.2.5 on 2025-10-30 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_room_designer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='For guest users', max_length=40, null=True)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('view_product', 'View Product'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('place_order', 'Place Order'), ('cancel_order', 'Cancel Order'), ('return_order', 'Return Order'), ('add_to_wishlist', 'Add to Wishlist'), ('remove_from_wishlist', 'Remove from Wishlist'), ('add_to_compare', 'Add to Compare'), ('remove_from_compare', 'Remove from Compare'), ('search', 'Search'), ('contact_form', 'Contact Form Submission'), ('review_product', 'Review Product'), ('update_profile', 'Update Profile'), ('change_password', 'Change Password'), ('page_view', 'Page View')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the activity')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_userac_user_id_efaa8e_idx'), models.Index(fields=['action', '-timestamp'], name='core_userac_action_b04fa7_idx'), models.Index(fields=['-timestamp'], name='core_userac_timesta_d4c17f_idx')],
            },
        ),
    ]
