# Generated by Django 5.2.5 on 2025-11-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_cancelled_at_order_dispatched_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(help_text='Name of the vendor', max_length=200)),
                ('product_purchased', models.CharField(help_text='Name of the product purchased from vendor', max_length=200)),
                ('quantity_purchased', models.PositiveIntegerField(help_text='Quantity purchased from this vendor')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price per unit paid to vendor', max_digits=10)),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, help_text='Total amount for this purchase (price * quantity)', max_digits=10)),
                ('payment_made', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already paid to vendor', max_digits=10)),
                ('balance_remaining', models.DecimalField(decimal_places=2, help_text='Remaining balance to be paid', max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date when payment record was created')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('category', models.ForeignKey(to='core.Category', on_delete=models.CASCADE, default=1)),
            ],
            options={
                'verbose_name': 'Vendor Payment',
                'verbose_name_plural': 'Vendor Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the purchased product', max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Price per unit of the product', max_digits=10)),
                ('product_quantity', models.PositiveIntegerField(help_text='Quantity purchased')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (price * quantity)', max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of purchase')),
                ('product_category', models.ForeignKey(help_text='Category of the purchased product', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Product Purchase',
                'verbose_name_plural': 'Product Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
