# Generated by Django 5.2.5 on 2025-11-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_vendorpayment_productpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product', max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Price per unit of the product', max_digits=10)),
                ('product_quantity', models.PositiveIntegerField(help_text='Quantity purchased/added to stock')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (price * quantity)', max_digits=10)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current available stock')),
                ('supplier_name', models.CharField(blank=True, help_text='Supplier or vendor name', max_length=200)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of purchase/stock addition')),
                ('product', models.OneToOneField(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, related_name='stock_management', to='core.product')),
                ('product_category', models.ForeignKey(help_text='Category of the product', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Stock Management',
                'verbose_name_plural': 'Stock Management',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.DeleteModel(
            name='ProductPurchase',
        ),
    ]
