# Generated by Django 5.2.5 on 2025-11-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_stockmanagement_delete_productpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the product purchased', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
