# Generated by Django 5.2.5 on 2025-11-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_vendorpayment_category'),
    ]

    operations = [
    ]
