# Generated by custom edit

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_product_to_vendorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmanagement',
            name='product',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='core.product', help_text='Associated product (set when deployed)'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='category',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.category', help_text='Category of the product purchased'),
        ),
    ]


