# Generated by custom edit

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_stockmanagement_product_and_vendorpayment_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='vendorpayment',
                    name='product',
                    field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', help_text='Linked product if applicable'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='product',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', help_text='Linked product if applicable'),
        ),
    ]


