# Generated by custom edit

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_optional_product_to_vendorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayment',
            name='product',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', help_text='Linked product if applicable'),
        ),
    ]


