# Generated by Django 5.2.5 on 2025-11-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_vendorpayment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayment',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Linked product if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
