# Generated by Django 5.2.5 on 2025-11-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_vendor_alter_vendorpayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True),
        ),
    ]
