"""
Django settings for furnex project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# BASIC CONFIGURATION
# =========================
SECRET_KEY = 'django-insecure-=a3df65dtwu3kl=2a^^ungv+ec6frxank4s73btoco8&tt@rnp'
DEBUG = True
ALLOWED_HOSTS = []


# =========================
# APPLICATIONS
# =========================
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
]


# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SimpleSessionCookieMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================
# URLS / WSGI
# =========================
ROOT_URLCONF = 'furnex.urls'
WSGI_APPLICATION = 'furnex.wsgi.application'


# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'furnex.settings_context.offline_mode',
            ],
            'builtins': [
                'django.templatetags.static',
            ],
        },
    },
]


# =========================
# DATABASE
# =========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =========================
# PASSWORD VALIDATION
# =========================
AUTH_PASSWORD_VALIDATORS = []  # All disabled for easy registration


# =========================
# INTERNATIONALIZATION
# =========================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# =========================
# STATIC & MEDIA FILES
# =========================
STATIC_URL = '/static/'

# Folder where collectstatic will put all files
STATIC_ROOT = BASE_DIR / "staticfiles"

# Folders where Django looks for static files in development
PROJECT_STATIC = BASE_DIR / "static"
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",         # app-level static
]
if PROJECT_STATIC.is_dir():
    STATICFILES_DIRS.append(PROJECT_STATIC)  # add project-level static only if it exists

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# =========================
# DEFAULTS
# =========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================
# JAZZMIN ADMIN SETTINGS
# =========================
JAZZMIN_SETTINGS = {
    "site_title": "Furnex Admin",
    "site_header": "Furnex Administration",
    "site_brand": "Furnex",
    "welcome_sign": "Welcome to Furnex Admin",
    "site_logo": "images/furnex-f-logo.svg",
    "login_logo": "images/furnex-f-logo.svg",
    "site_icon": "images/furnex-f-logo.svg",
    "copyright": "Furnex",
    "icons": {
        "core": "fas fa-couch",
        "core.Category": "fas fa-layer-group",
        "core.Product": "fas fa-box-open",
        "core.ProductDimension": "fas fa-ruler-combined",
        "core.Review": "fas fa-star",
        "core.Compare": "fas fa-compress-arrows-alt",
        "core.Wishlist": "fas fa-heart",
        "core.Order": "fas fa-box",
        "core.OrderItem": "fas fa-list",
        "core.Coupon": "fas fa-percent",
        "core.UserCoupon": "fas fa-gift",
        "core.UserActivity": "fas fa-clipboard-list",
        "core.UserAddress": "fas fa-map-marker-alt",
        "core.UserNotification": "fas fa-bell",
        "core.Contact": "fas fa-envelope",
        "core.ChatConversation": "fas fa-comments",
        "core.ChatMessage": "fas fa-comment-dots",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "order_with_respect_to": [
        "core",
        "auth",
    ],
    "side_menu": [
        { "name": "Dashboard", "url": "admin:index", "icon": "fas fa-tachometer-alt" },
        { "app": "core", "label": "Products", "icon": "fas fa-box-open", "models": [
            "core.Product",
            "core.ProductDimension",
            "core.Category",
            "core.Review",
            "core.Compare",
            "core.Wishlist"
        ]},
        { "app": "core", "label": "Orders", "icon": "fas fa-box", "models": [
            "core.Order",
            "core.OrderItem"
        ]},
        { "app": "core", "label": "Promotions", "icon": "fas fa-percent", "models": [
            "core.Coupon",
            "core.UserCoupon"
        ]},
        { "app": "core", "label": "Users", "icon": "fas fa-user", "models": [
            "auth.User",
            "auth.Group",
            "core.UserActivity",
            "core.UserAddress",
            "core.UserNotification"
        ]},
        { "app": "core", "label": "Communication", "icon": "fas fa-comment-dots", "models": [
            "core.Contact",
            "core.ChatConversation",
            "core.ChatMessage"
        ]},
        { "app": "core", "label": "System", "icon": "fas fa-cogs", "models": [] },
    ],
    "custom_css": "css/admin_overrides.css",
}


# =========================
# JAZZMIN UI TWEAKS
# =========================
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "accent": "accent-primary",
}


# =========================
# E-COMMERCE SETTINGS
# =========================
COD_EXTRA_FEE = 0
ORDER_DELIVERY_DAYS = 5


# =========================
# TWILIO (optional)
# =========================
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')


# =========================
# RAZORPAY CONFIG
# =========================
RAZORPAY_KEY_ID = 'rzp_test_R7ct4MyO5ZirHn'
RAZORPAY_KEY_SECRET = 'z3UdkkCzjUNR0M00tnTY7YHf'


# =========================
# EMAIL CONFIG
# =========================
# Offline-friendly defaults
OFFLINE_MODE = bool(os.getenv('OFFLINE_MODE', '0') in ['1', 'true', 'True'])

if OFFLINE_MODE:
    # Write emails to files locally so it works without internet
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = BASE_DIR / 'offline_emails'
    # Disable Razorpay keys in offline mode
    RAZORPAY_KEY_ID = ''
    RAZORPAY_KEY_SECRET = ''
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'thefurnexofficial@gmail.com'
EMAIL_HOST_PASSWORD = 'obzd xenj wpia osrk'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Uncomment for testing


# =========================
# SESSION SETTINGS
# =========================
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_DOMAIN = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# =========================
# AUTH / LOGIN
# =========================
LOGIN_URL = '/login/'

# =========================
# SECURITY (Production)
# =========================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# If behind a proxy/load balancer that sets X-Forwarded-Proto
if os.getenv('BEHIND_PROXY', '0') in ['1', 'true', 'True']:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
